### ISSUE TITLE
Add argument on config_bkup to backup on the root of ansible

### ISSUE THREAD

**Issue by hrv231** [aruba/aruba-ansible-modules#11]
I would like an option to be able to backup my running config to a file, meaning.. I would like a file to be created on whatever location I'm running ansible.
Example: 
user1@Computer:~/ansible$ pwd
/home/user1/ansible

If I run:
user1@Computer:~/ansible$ ansible-playbook aruba_backup_using_api.yaml
>  tasks:
>       - name: backup configuration files
>         arubaoss_config_bkup:
>           file_name: "{{ inventory_hostname}}"
>           config_type: CT_RUNNING_CONFIG

I would like the file to be created on `/home/user1/ansible` or any other location from where I run ansible-playbook.

**Comment by tchiapuziowong** [comment]
Hello!

Using our modules you can backup your configuration to a TFTP server hosted by your machine running Ansible. Then using other Ansible modules (not created by Aruba) you can move that file to another location on your machine.

Here's an example of how to use the arubaoss_config_bkup module to copy your configuration to a TFTP server:
```yaml
---
- hosts: switch1
  tasks:
    - name: backup config to tftp
      arubaoss_config_bkup:
        config_type: CT_RUNNING_CONFIG
        server_type: ST_TFTP
        server_ip: 10.20.2.15
        file_name: test.txt
```
