### ISSUE TITLE
arubaoss_reboot  "Could not get devcie status. Not rebooted!"

### ISSUE THREAD

**Issue by robertpriedl** [aruba/aruba-ansible-modules#110]
ansible version: 2.9
python version: 3.6

I am getting this error when running arubaoss_reboot. The error message is "Could not get devcie status. Not rebooted!"
Other arubaoss_ Tasks are working (like arubaoss_interface, arubaoss_vlan..)

My **inventory** with connection settings:
```
all:
  hosts:
    switch001:
      ansible_host: 10.20.220.200
      ansible_network_os: arubaoss
      ansible_connection: local
      ansible_user: test
      ansible_password: test123
```

My **playbook**:
```
---
- hosts: all
  tasks:
  - name: reboot device
    arubaoss_reboot:
      boot_image: BI_SECONDARY_IMAGE
      is_wait: False
```

the vvvv output of the playbook:
```connection transport is aossapi for 10.20.220.200
None is not valid api version. using aossapi v6.0 instead
<10.20.220.200> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.20.220.200> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.20.220.200> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902 && echo ansible-tmp-1592990341.4901884-11386-128318066366902="` echo /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/arubaoss/arubaoss_reboot.py
<10.20.220.200> PUT /root/.ansible/tmp/ansible-local-112983_jhgncf/tmpbbjkxw7g TO /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/AnsiballZ_arubaoss_reboot.py
<10.20.220.200> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/ /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/AnsiballZ_arubaoss_reboot.py && sleep 0'
<10.20.220.200> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/AnsiballZ_arubaoss_reboot.py && sleep 0'
<10.20.220.200> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/ > /dev/null 2>&1 && sleep 0'
fatal: [switch001]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "v7.0",
            "boot_image": "BI_SECONDARY_IMAGE",
            "host": "10.20.220.200",
            "is_wait": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 80,
            "provider": {
                "api_version": null,
                "host": "10.20.220.200",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 80,
                "ssh_keyfile": null,
                "timeout": 30,
                "transport": "aossapi",
                "use_proxy": false,
                "use_ssl": false,
                "username": "test",
                "validate_certs": false
            },
            "ssh_keyfile": null,
            "timeout": 30,
            "use_ssl": false,
            "username": "test",
            "validate_certs": false
        }
    },
    "msg": "Could not get devcie status. Not rebooted!"
```
How can i getting the reboot working?

robert
