### ISSUE TITLE
Support for prompt in arubaoss_command

### ISSUE THREAD

**Issue by EarlRamirez** [aruba/aruba-ansible-modules#129]
Automating backup with ansible has been a bit challenging with the arubaoss_command module.

When using SCP to copy config and flash backup the controllers prompts for a password and without this option, the copy fails.

 Below is a sample playbook to perform this task.
```yaml
---
- name: Backup Aruba Configuration
  hosts: wlc
  gather_facts: false
  serial: 1

  tasks:
    - name: Create backup on controllers
      arubaoss_command:
        commands:
          - "backup {{ item }}"
      loop:
        - config
        - flash

    - name: Save backup configuration to disk
      arubaoss_command:
        commands:
          - "copy flash: {{ item.src_file }} scp: {{ item.src_addr }} {{ item.user }}  {{ inventory_hostname }}_{{ item.dst_file }}"
            prompt: "Password:"
            answer: "{{ backup_pass }}"
      loop: "{{ backup_vars }}"
```
