### ISSUE TITLE
Stuck with : Request failed: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by Cannasteve** [aruba/aruba-ansible-modules#136]
Hello everyone, i'm stuck with this error  : 

```
fatal: [switch1]: FAILED! => {"changed": false, "msg": "Request failed: <urlopen error [Errno -2] Name or service not known>", "status": -1, "url": "https://None:443/rest/v6.0/login-sessions"}
```

The FAQ page here section Environnement FAQ mention to reinstall aos_wired modules with python, but i'have installed it through Galaxy with this command: `ansible-galaxy collection install arubanetworks.aos_switch`

```
manager@ansible:/$ ansible-galaxy collection list | grep aruba
arubanetworks.aos_switch 1.5.0
```

I've try to force reinstall with --force arg but i have the same issue.

My switch is an Aruba 2930F JL256A (WC 16.10.000) rest interface all is Up /enabled

```manager@ansible:/$ ansible --version
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/manager/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/manager/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/manager/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/manager/.local/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

I don't know what to do now :(  I would appreciate it if you could help me.

Regards, Steve D.

**Comment by alagoutte** [comment]
What your Inventory file and playbook ?

**Comment by tchiapuziowong** [comment]
Hi @Cannasteve !

Please use this repository https://github.com/aruba/aos-switch-ansible-collection instead of the one this issue is opened on. That is the most recent and most supported integration of AOS-Switch and Ansible.

If you follow the Collection's README you'll see a section regarding [Setting Environment Variables](https://github.com/aruba/aos-switch-ansible-collection#setting-environment-variables) can you ensure you've done that step?

**Comment by Cannasteve** [comment]
Hello, thanks for replying so fast :)

@alagoute
> What your Inventory file and playbook ?



My inventory file look like this:

```
all:
  hosts:
    switch1:
      ansible_host: [10.150.XXX.XX]
      ansible_user: [LOGIN]
      ansible_password: [PASSWORD]
      ansible_connection: network_cli  # Do not change
      ansible_network_os: arubanetworks.aos_switch.arubaoss  # Do not change
```
Here i add the line ansible_network_os:

and here is my last playbook test for vlan creation:

```
---
- hosts: switch1
  collections:
    - arubanetworks.aos_switch
  tasks:
      - name: Create VLAN `XXX
        arubaoss_vlan:
          vlan_id: XXX
          name: "VLAN_B"
          config: "create"
          command: config_vlan
          api_version: v6.0
          use_ssl: True
```
i add the lines "collections:",  "api_version:" and  "use_ssl:"
           
@tchiapuziowong
Yes i follow that step in my ansible.cfg i add:
```
[defaults]
NETWORK_GROUP_MODULES=arubaoss
```
