### ISSUE TITLE
firmware upgrade through ssh cli

### ISSUE THREAD

**Issue by hrv231** [aruba/aruba-ansible-modules#28]
Hello,

Following all the documentation from: https://github.com/aruba/aruba-switch-ansible
I tried to test the upgrade using the example provided and it is not working, it seems that all your examples are based on the way you guys have setup the inventory.
I would like to know how to upgrade the switches using the arubaos_switch_ssh_cli .
Below is an example of my playbook to use to upgrade a switch:
```
---
- name: Upgrade
  hosts: HP2530-24G-PoE,
  gather_facts: no
  connection: local
  tasks:
    - name: Upgrade Firmware via SSH CLI
      arubaos_switch_ssh_cli:
        ip: "{{ansible_host}}"
        user: "{{ansible_user}}" 
        password: "{{ansible_password}}"
        # path_to_swi, boot_image and enable_sftp have to be given at once otherwise the module will fail.
      include: aruba_task_lists/aos_switch/firmware_upgrade.yml
      vars:
        ip: "{{ansible_host}}"
        host_ip: "10.10.10.25"
        path_to_swi: "./files/YA_16_06_0006.swi"
        boot_image: "primary"
        enable_sftp: True # If True is given, the system will enable ssh filetransfer and disable tftp | If False is given the system has to have ssh filetransfer enable otherwise the module will stop
        state: "upgrade"

```

How can I accomplish this?
What I want to do is to upgrade the switch or switches via cli using ssh filetransfer, without having to spin up a website.

**Comment by hrv231** [comment]
Alright..
Finally my playbook started running:
```
---
- name: Upgrade
  hosts: HP2530-24G-PoE,
  gather_facts: no
  connection: local
  tasks:
    - name: Upgrade Firmware via SSH CLI
      include: aruba_task_lists/aos_switch/firmware_upgrade.yml
      vars:
        ip: "{{ansible_host}}"
        user: "{{ansible_user}}" 
        password: "{{ansible_password}}"
        path_to_swi: "files/YA_16_06_0006.swi"
        boot_image: "primary"
        enable_sftp: True
        state: "upgrade"
      register: module_result
```

But after "Check current Firmware Version" I get an error:
```
TASK [Check current Firmware Version] *******************************************************************************************************************************************************************************
ok: [HP2530-24G-PoE]

TASK [set_fact] *****************************************************************************************************************************************************************************************************
fatal: [HP2530-24G-PoE]: FAILED! => {"msg": "template error while templating string: no filter named 'find_version'. String: {{ (ssh_output.cli_output[0] | replace(\" \", \"\")) | find_version( boot_image )  | replace(\".\",\"_\") }}"}
```

Can you please tell me how to fix this?

**Comment by tchiapuziowong** [comment]
Hi @hrv231 ! It looks like your playbook is having trouble finding the file https://github.com/aruba/aruba-switch-ansible/blob/master/filter_plugins/aos_switch_filters.py

is the filter_plugins directory in the same one as where you have your playbook?

**Comment by hrv231** [comment]
Thank you Tiffany for replying this fast.
No, is not on the same directory.
I followed all the documentation it is here:
https://community.arubanetworks.com/t5/Developer-Community/How-to-install-use-CLI-modules-and-tasks-for-Switch-and-CX-in/td-p/534333
and I didn't see anything pointing to the filters.

Also.. I had to comment the below set_fact:
```
# - set_fact:
#     url_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
- set_fact:
    url_ip: "{{ host_ip }}"
  when: host_ip is defined
```
because my inventory is like this:
```
all:
  children:
    device_roles_Access_Switch:
      hosts:
        2200HP2530-48G-1:
          ansible_host: 10.10.10.10
          ansible_ssh_pass: passw1
          ansible_user: admin
          device_roles:
          - Access_Switch
          device_types:
          - 2530-48G-PoE+
          manufacturers:
          - HP
          platforms:
          - ArubaOS
          primary_ip4: 10.10.10.10
          sites:
          - School1
```

so it is not finding ansible_default_ipv4 , should I change that line to:
```
# - set_fact:
#     url_ip: "{{ hostvars[inventory_hostname]['primary_ip4'] }}"

```

**Comment by tchiapuziowong** [comment]
Ah okay that makes sense! That document talks about using the SSH module in your own playbook, but in regards to using the workflows or the task lists, it assumes you're in the working directory of the cloned repo [Aruba Switching Ansible Workflow](https://github.com/aruba/aruba-switch-ansible) . That includes the task_lists and the filter_plugins.

Try copying over the filter_plugins directory (keep the name convention that's very important) , then try running again!

**Comment by hrv231** [comment]
I did that, and now it throws another error:
![image](https://user-images.githubusercontent.com/41212308/60463448-dfc9fb00-9c00-11e9-9f1e-04e54a495607.png)

**Comment by hrv231** [comment]
Tiffany,

I discovered the error in your Code.
I managed to change the filter plugin to:
```
def find_version(serach_string, version):
    """
    Return the current SWI Version of the selected Image
    :param serach_string: string that shall be looked through
    :param version: string for one of the following (primary,secondary,primary_boot,secondary_boot)
    :return: SWI Version as string
    """
    regex = u"YA\.[0-9]{2}\.[0-9]{2}\.[0-9]{4}"
```
from WC to YA, and finally the playbook ran well:
```
TASK [debug] ********************************************************************************************************************************************************************************************************
task path: /home/user1/ansible/aruba_task_lists/aos_switch/firmware_upgrade.yml:58
ok: [HP2530-24G-PoE] => {
    "msg": "To be Version: YA_16_06_0006"
}

TASK [fail] *********************************************************************************************************************************************************************************************************
task path: /home/user1/ansible/aruba_task_lists/aos_switch/firmware_upgrade.yml:64
fatal: [HP2530-24G-PoE]: FAILED! => {
    "changed": false, 
    "msg": "Switch shall be upgraded but to be version is lower than or equal to current version. Unable to upgrade."
}

PLAY RECAP **********************************************************************************************************************************************************************************************************
HP2530-24G-PoE         : ok=6    changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
```

Now the problem is that you guys coded to the two characters of the switch version as WC, and as you probably know, the aruba switches have different firmware versions with different two letters:
WC
YA
YC
KB
WC
WB
K
KB

Would be nice if you guys can change the code, in a way that will compare the first with the file given by the playbook on the **path_to_swi**.

Thanks.

**Comment by tchiapuziowong** [comment]
Hey @hrv231 ! Yes I noticed that same issue! The playbook did throw an error about the passed in version value being lower or at the same version as the current version, was it able to work after that?

**Comment by hrv231** [comment]
Interesting, now I see that there has to be a problem with the way the connection is made.
I'm trying to run the same playbook to other aruba 2530 device but that it is on another network, and for some reason the module fails, all the time it fails.
It doesn't fail when the switch is on the same network as the host running ansible.

**Comment by tchiapuziowong** [comment]
@hrv231  Are you able to ping the device you're attempting to run Ansible with?

**Comment by hrv231** [comment]
Yes, I'm able to ping the devices and I'm able to use SSH with putty to them.
I'm also able to use the aruba_config that is included within ansible, which it is different than yours.

**Comment by hrv231** [comment]
Hi @tchiapuziowong , I have been doing some tests, and it seems that the problem is with the code **show_command** , for different networks and also different types of aruba switches, the show_command works and for others do not work.

For example, if I run:
```
- name: Get output of show flash
  arubaos_switch_ssh_cli:
    ip: "{{ansible_host}}"
    user: "{{ansible_user}}" 
    password: "{{ansible_password}}"
    show_command: ["show flash"]
  register: ssh_output
```

It will work for some switches, but not for all.
But if I run:
```
- name: Get output of show flash
  arubaos_switch_ssh_cli:
    ip: "{{ansible_host}}"
    user: "{{ansible_user}}" 
    password: "{{ansible_password}}"
    command_list: ["show flash"]
  register: ssh_output
```
It will run on all the switches.
