### ISSUE TITLE
arubaoss radius server config

### ISSUE THREAD

**Issue by fallenfuzz** [aruba/aruba-ansible-modules#32]
sabj is missing or i'm blind :)

Thanks

**Comment by fallenfuzz** [comment]
found something under arubaoss_radius_profile.py, will test.

**Comment by tchiapuziowong** [comment]
Hi @fallenfuzz ! I'm a little confused what the issue is, would you mind posting your error?

**Comment by fallenfuzz** [comment]
so, in this module we have 3 options:

config_radius_profile - this is the general profile i assume
config_radius_serverGroup - this on is to create a group with radius
config_radius_server - this one is ONLY to update already existing profile, it doesn't create a new, config: create option also doesn't give anything.

So maybe we should have 3 option for config: create, update and delete

What is required is to create just radius config, for example (taken from sw config):
radius-server host 10.0.0.1 key "RADIUS!"

**Comment by tchiapuziowong** [comment]
Hi @fallenfuzz so after some investigation it appears this is in fact a bug, you should be able to create the radius server without it already being configured on the device.

We're working on a solution and will update with a commit to the fixed issue.

**Comment by fallenfuzz** [comment]
Hey @tchiapuziowong just a kind nudge :)

**Comment by tchiapuziowong** [comment]
@fallenfuzz will be looking into fixing this next week! apologies for the delay!

**Comment by tchiapuziowong** [comment]
Hi @fallenfuzz !!!

Here is an example of how to configure radius-server host 10.0.0.1 key "RADIUS!" using the module arubaoss_radius_profile : 
```
    - name: Configure Radius server 10.0.0.1 with shared secret RADIUS!
      arubaoss_radius_profile:
        command: config_radius_server
        server_ip: 10.0.0.1
        shared_secret: "RADIUS!"
````

I've also updated the module documentation and examples to be more descriptive and helpful! https://github.com/aruba/aruba-ansible-modules/commit/ae0fbe85ab8b17a3ee3d3a4a44e76eefe5285037
