### ISSUE TITLE
arubaoss_vlan delete config_vlan_ipaddress does not work

### ISSUE THREAD

**Issue by falkheiland** [aruba/aruba-ansible-modules#45]
```yml
  - name: Remove IP-Address VLAN 300
    arubaoss_vlan:
      vlan_id: 300
      config: "delete"
      command: config_vlan_ipaddress
      vlan_ip_address: "192.168.0.1"
      vlan_ip_mask: "255.255.255.0
```

according to the 3rd [example](https://github.com/aruba/aruba-ansible-modules/blob/master/example_playbooks/arubaoss/vlan.yml)

YA.16.09.0003
HP J9854A

deleting the entire vlan works. setting the ip address works.
