### ISSUE TITLE
Please provide example for IP Address Mode to be configured on vlan using IAAM_DHCP

### ISSUE THREAD

**Issue by falkheiland** [aruba/aruba-ansible-modules#50]
I am trying to set a DHCP address on a vlan but cant figure out how to do so.
I tried:

```yml
- name: Set vlan 300 ipv4 address to DHCP
    arubaoss_vlan:
      command: config_vlan_ipaddress
      vlan_id: 300
      version: "IAV_IP_V4"
      ip_address_mode: "IAAM_DHCP"
```

I get the message: 
```
fatal: [xxxxx]: FAILED! => {"changed": false, "msg": "IP Address or version cannot be null"}
```
