### ISSUE TITLE
Cannot remove port from default VLAN

### ISSUE THREAD

**Issue by andusvan** [aruba/aruba-ansible-modules#55]
Hello!

I'm trying to remove a Port (No. 6), which is assigned to another VLAN (ID: 10), from the DEFAULT_VLAN (ID: 1).
In the CLI it works with the following two commands:
```
vlan 1 untagged 6
no vlan 1 untagged 6
```

I tried this playbook:

```
---
 - hosts: switch1
   tasks:

    - name: Set Port 6 untagged 6 on VLAN 1
      arubaoss_vlan:
        command: config_vlan_port
        config: create
        vlan_id: 1 
        port_id: 6
        port_mode: POM_UNTAGGED

    - name: Delete untagged 6 on VLAN 1
      arubaoss_vlan:
        command: config_vlan_port
        config: delete
        vlan_id: 1 
        port_id: 6
        port_mode: POM_UNTAGGED
```

This is my current running config:
```
Running configuration:

; JL323A Configuration Editor; Created on release #WC.16.09.0004
; Ver #14:27.6f.f8.1d.9b.3f.bf.bb.ef.7c.59.fc.6b.fb.9f.fc.ff.ff.37.ef:04

hostname "ArubaSwitch"
module 1 type jl323a
aruba-central disable
max-vlans 2048
time timezone 180
web-management ssl
ip ssh filetransfer
ip routing
interface 11
   name "UPLINK_INTERFACE"
   exit
snmp-server community "public" unrestricted
oobm
   ip address dhcp-bootp
   ipv6 enable
   ipv6 address dhcp full
   exit
vlan 1
   name "DEFAULT_VLAN"
   no untagged 3
   untagged 2
   tagged 1,4-48
   ip address 172.16.0.101 255.255.255.0
   exit
vlan 10
   name "TEST"
   tagged 3,6
   no ip address
   exit
no tftp client
no tftp server
no autorun
no dhcp config-file-update
no dhcp image-file-update
password manager

```
If I run the playbook the first command works.
The second command gives me: "Port association with default vlan cannot be removed"

How do I achieve this with the Ansible or the REST-API?
I think there is a command missing in the Playbook or even the REST-API...

Any help appreciated!

Regards
 Sven

**Comment by tchiapuziowong** [comment]
Hi Sven!

I might be confused by your ask. In CLI you're unable to untag a port on VLAN 1, when a port is untagged on another VLAN, it's automatically untagged on VLAN 1. If you untag the port on any other VLAN than VLAN 1 it will by default go back to being untagged on VLAN1.

In this config, if I were to go into vlan 10 and execute 'no untagged 4' it will then go to VLAN 1 untagged:
````
vlan 1
   name "DEFAULT_VLAN"
   no untagged 4
   untagged 1-3,5-24
   ip address dhcp-bootp
   ipv6 enable
   ipv6 address dhcp full
   exit
vlan 10
   name "VLAN10"
   untagged 4
   no ip address
   exit
Aruba-3810M-24G-1-slot(vlan-10)# no untagged 4

4:These ports are moved to default VLAN.
Aruba-3810M-24G-1-slot(vlan-10)#
vlan 1
   name "DEFAULT_VLAN"
   untagged 1-24
   ip address dhcp-bootp
   ipv6 enable
   ipv6 address dhcp full
   exit
vlan 10
   name "VLAN10"
   no ip address
   exit
no tftp server
```

And if I go to VLAN 1 and execute 'no untagged 4' I receive the same error you received:
```
vlan 1
   name "DEFAULT_VLAN"
   untagged 1-24
   ip address dhcp-bootp
   ipv6 enable
   ipv6 address dhcp full
   exit
vlan 10
   name "VLAN10"
   no ip address
   exit
Aruba-3810M-24G-1-slot(vlan-1)# no untagged 4
Ports 4 would be orphaned. No ports removed.
Aruba-3810M-24G-1-slot(vlan-1)#
```

In AOS-Switch, the only way to have a port completely off of VLAN 1 would be to have it untagged and tagged on different VLANs.

Let me know if I'm completely wrong in understanding the issue :)

**Comment by andusvan** [comment]
Hello!

I'm currently using this AOS-Switch for testing:
HPE Aruba 2930M 40G 8SR PoE+ Switch (JL323A) 

> In AOS-Switch, the only way to have a port completely off of VLAN 1 would be to have it untagged and tagged on different VLANs.

This is not right. You can have a port tagged on one vlan and can declare it "no untagged" on the VLAN 1.

Example:

; JL323A Configuration Editor; Created on release #WC.16.09.0004
; Ver #14:27.6f.f8.1d.9b.3f.bf.bb.ef.7c.59.fc.6b.fb.9f.fc.ff.ff.37.ef:04

hostname "ArubaSwitch"
aruba-central disable
max-vlans 2048
web-management ssl
ip ssh filetransfer
ip routing
snmp-server community "public" unrestricted
vlan 1
   name "DEFAULT_VLAN"
   no untagged 2
   tagged 1,3-48
   ip address 172.16.0.101 255.255.255.0
   exit
vlan 2
   name "TEST"
   tagged 2
   no ip address
   exit

This is what I want to configure with ansbile too.

**Comment by andusvan** [comment]
My example here is similar to your first example.
So, how do you configure your first example with aruba-ansible?
Do you have a playbook for this (starting with an complete unconfigured switch, i.e. all ports on the default vlan)?

**Comment by tchiapuziowong** [comment]
Hi @andusvan !

Ah okay I think I understand the ask now, when dealing with VLAN 1 we want to set the port_mode to be "POM_FORBIDDEN" - this will give us the "no untagged" result.

Here is the playbook:
```
---
- hosts: switch1
  gather_facts: False
  tasks:
    - name: Create VLAN 2
      arubaoss_vlan:
        vlan_id: 2
        command: config_vlan

    - name: Tag port 2 on vlan 2
      arubaoss_vlan:
        vlan_id: 2
        command: config_vlan_port
        port_mode: "POM_TAGGED_STATIC"
        port_id: "2"

    - name: No UnTagged port 2 on vlan 1
      arubaoss_vlan:
        vlan_id: 1
        command: config_vlan_port
        port_mode: "POM_FORBIDDEN"
        port_id: "2"
```

Here is the CLI:
```
vlan 1
   name "DEFAULT_VLAN"
   no untagged 2
   untagged 1,3-24,A1-A4
   ip address dhcp-bootp
   ipv6 enable
   ipv6 address dhcp full
   forbid 2
   exit
vlan 2
   name "VLAN2"
   tagged 2
   no ip address
   exit
```
Let me know if this is the solution you were looking for!

**Comment by andusvan** [comment]
Hello!

That's _almost_ what I'm looking for. But the "forbid 2" would prevent the port 2 to join the default VLAN, if this was advertised via GVRP.
The main reason I want to use the "no untagged 2" setting on VLAN 1 is, that I do not want the default VLAN1 traffic on a switch's uplink port (i.e. connection between switches).
But I do not want to make any other restrictions on this port, because in some scenario it might be useful to have a specific VLAN on VLAN1 too (configured via GVRP).

All I want is to be able to set the same settings via Ansible that I can set via the CLI...

**Comment by AWegner1** [comment]
Hey,

same problem here.
I am unable to set the "no untagged vlan x" state without using POM_FORBID in the rest api.
Maybe connected issue?

**Comment by alagoutte** [comment]
no untagged vlan X is not equal forbidden vlan ?

**Comment by andusvan** [comment]
No, it's not the same, as stated in my last comment.

**Comment by AWegner1** [comment]
forbid adds extra "forbidden" behaviour while no untagged vlan X just removes the untagged vlan from the port

**Comment by alagoutte** [comment]
Hi,

after a quick check, if you affect a untagged port on new vlan, it is automally set no untagged  X on vlan 1

> switch# vlan 4
> switch(vlan-4)# untagged 3
> switch(vlan-4)# show running-config 
>[...]
>vlan 1
>   name "DEFAULT_VLAN"
>   no untagged 3
>   untagged 1-2,4-10
>
>vlan 4
>   name "VLAN4"
>   untagged 3

and why API (and PowerArubaSW) :
```powershell
 Get-ArubaSWVlansPorts -port_id 3
uri              vlan_id port_id port_mode
---              ------- ------- ---------
/vlans-ports/4-3       4 3       POM_UNTAGGED           
```

**Comment by tchiapuziowong** [comment]
Hi @andusvan !

Following up again it seems like what you're trying to achieve can be done through a sequence of commands:

```yaml
    - name: Create VLAN 10
      arubaoss_vlan:
        vlan_id: 10
        command: config_vlan

    - name: Untagged port 3 on vlan 10
      arubaoss_vlan:
        vlan_id: 10
        command: config_vlan_port
        port_mode: "POM_UNTAGGED"
        port_id: "3"

    - name: Tag port 3 on vlan 10
      arubaoss_vlan:
        vlan_id: 10
        command: config_vlan_port
        port_mode: "POM_TAGGED_STATIC"
        port_id: "3"
```

This will result in the following CLI:

```bash
vlan 1
   name "DEFAULT_VLAN"
   no untagged 3
   untagged 1-2,4-24
   ip address dhcp-bootp
   ipv6 enable
   ipv6 address dhcp full
   exit
vlan 10
   name "VLAN10"
   tagged 3
   no ip address
   exit
```
