### ISSUE TITLE
ClearPass Download User Role

### ISSUE THREAD

**Issue by wazzfi** [aruba/aruba-ansible-modules#58]
I might have just missed it but where do we create a ClearPass download role?

radius-server cppm.....

**Comment by tchiapuziowong** [comment]
Hello!

Here's an example of how to configure the cppm details - 
```
    - name: Configure Radius Profile CPPM details for User Roles
      arubaoss_radius_profile:
        command: config_radius_profile
        cppm_details: {'username':'superman','password': 'upupandaway'}
```

I've also updated the module documentation and examples to be more descriptive and helpful! ae0fbe8
