### ISSUE TITLE
CPPM: Token Authentication

### ISSUE THREAD

**Issue by sachaboudjema** [aruba/aruba-ansible-modules#59]
It would be nice to be able to set the access token directly instead of having to enter client credentials. This way you don't have to pass the credentials around, you just ask an admin for a 3h token and you can have your fun.

It also would have the advantage of not generating a token for each call to the module.

A call could then look like this:

```
arubaclearpass_config:
      host: "{{ publisher_ip }}"
      token: "{{ api_token }}"
      method: POST
      api_name: network-device
      data: {....}
```
