### ISSUE TITLE
ArubaOSS : Use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by louisfrancoisSO** [aruba/aruba-ansible-modules#7]
Hello,

I'm trying your module on my 2930F  but the connection get refused because it only tries in HTTP.
On my 2930F, HTTP is disabled and I can't figured out how to force your module to go through HTTPS.

> THIRD(config)# show rest-interface
> 
>  REST Interface - Server Configuration
> 
>   REST Interface            : Enabled
>   REST Operational Status   : Up
>   REST Session Idle Timeout : 7200 seconds
>   HTTP Access               : Disabled
 >  HTTPS Access              : Enabled
 >  SSL Port                  : 443

My switch_host.yml is like in the example given and the playbook is the creation of one VLAN, so quite basic.

The error :
> TASK [Create VLAN 300] *********************************************************
> fatal: [switch1]: FAILED! => {"changed": false, "msg": "Request failed: <urlopen error timed out>", "status": -1, "url": "http://172.17.104.13:80/rest/version"}

The address should not use HTTP and port 80 but rather HTTPS and port 443.
Where and what should I add to force using SSL ?

**Comment by tchiapuziowong** [comment]
Hello! The module uses HTTP to retrieve the api_version of the device when it's not provided. Try providing the api_version as a parameter to each module call to see if that resolves your issue.

Your task would look like this:
```yaml
- name: Create VLAN 300
  arubaoss_vlan:
    vlan_id: 300
    name: "vlan300"
    config: "create"
    command: config_vlan
    api_version: v6.0
```

**Comment by tchiapuziowong** [comment]
You can also pass in the use_ssl parameter as well:

```yaml
- name: Create VLAN 300
  arubaoss_vlan:
    vlan_id: 300
    name: "vlan300"
    config: "create"
    command: config_vlan
    api_version: v6.0
    use_ssl: True
```
