### ISSUE TITLE
arubaoss :: filebackup

### ISSUE THREAD

**Issue by wazzfi** [aruba/aruba-ansible-modules#73]
(wish there was a "question" section instead of "issues" but in any event)

:-)

Is there a way to have the file_name the hostname of the switch? i.e. add a variable in the file_name field.

      - name: backup configuration files
        arubaoss_config_bkup:
          file_name: test1
          server_type: ST_TFTP
          server_ip: 192.168.1.2
      - name: backup configuration files
        arubaoss_config_bkup:
          file_name: test1
          config_type: CT_RUNNING_CONFIG

**Comment by tchiapuziowong** [comment]
Hi @wazzfi !!

Refer to either [this video](https://www.youtube.com/watch?v=XJocMWbnvvM&list=PLsYGHuNuBZcYeIau1dEfWEretD9S9OCqu&index=3) or [this Ansible article](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html) on How to Use Variables in Ansible. But for your supplied example, let's say we want to use the name of the device in Ansible's inventory, we could use the special variable `inventory_hostname` OR if you have a variable defined in your inventory, let's say `device_hostname` this would be the solution:
```
  - name: backup configuration files using Ansible defined special variable inventory_hostname
    arubaoss_config_bkup:
      file_name: "{{ inventory_hostname }}"
      server_type: ST_TFTP
      server_ip: 192.168.1.2

  - name: backup configuration files using user defined inventory variable device_hostname
    arubaoss_config_bkup:
      file_name: "{{ device_hostname }}"
      server_type: ST_TFTP
      server_ip: 192.168.1.2
```



In regards to 'How-To' questions, our [Airheads developer community](https://community.arubanetworks.com/t5/Developer-Community/bd-p/DeveloperCommunity) is the best place for that!!
