### ISSUE TITLE
arubaoss  arubaoss_acl_policy

### ISSUE THREAD

**Issue by zenchaos** [aruba/aruba-ansible-modules#82]
When the source or destination are specified in cidr notation or any, the module doesn't detect that a change has to be made.  The acl will be added but the acl will be empty.

    - name: Allow access rule
      arubaoss_acl_policy:
        acl_name: Test
        source_ip_address: any
        destination_ip_address: 192.168.1.0/24
        protocol_type: PT_IP
        acl_action: AA_PERMIT
        acl_type: AT_EXTENDED_IPV4

The switch OS allows you to specify either in cidr notation or any.

How can the destination port be specified?  I couldn't find documentation how to specify if the port was a gt, lt, eq, range etc.

The following doesn't work to allow dhcp:

    - name: Extended acl allow dhcp
      arubaoss_acl_policy:
        acl_name: Phone
        source_ip_address: 0.0.0.0
        source_ip_mask: 255.255.255.255
        destination_ip_address: 0.0.0.0
        destination_ip_mask: 255.255.255.255
        protocol_type: PT_UDP
        destination_port: 67
        acl_action: AA_PERMIT
        acl_type: AT_EXTENDED_IPV4

**Comment by tchiapuziowong** [comment]
Hi @zenchaos !

When creating an entry to match "any" it's required to use `0.0.0.0` for source/destination IP address and then specifying `255.255.255.255` for the mask in octet form. This is expected behavior since this is the expected format for the REST API.

For the source / destination port , you'll need to provide a dictionary containing the keys `port_not_equal` , `port_range_start`, and `port_range_end`. I've updated the module documentation and example playbook `acl.yml` to properly document this behavior and how to use it.

To achieve the configuration to allow DHCP this would be correct solution:
```YAML
    - name: Extended acl allow dhcp
      arubaoss_acl_policy:
        acl_name: permit_port_80
        source_ip_address: 0.0.0.0
        source_ip_mask: 255.255.255.255
        protocol_type: PT_TCP
        source_port:
          port_not_equal: 0       # Set to 0
          port_range_start: 80    # Set to equal port
          port_range_end: 80      # Set to equal port
        destination_ip_address: 0.0.0.0
        destination_ip_mask: 255.255.255.255
        destination_port: {"port_not_equal": 0,"port_range_start": 80,"port_range_end": 80}     # another way to pass a dictionary
        acl_action: AA_PERMIT
        acl_type: AT_EXTENDED_IPV4
```

https://github.com/aruba/aruba-ansible-modules/commit/02c6eaf44d022a4854c3eb24003047f753d8bbbb
